# Generated by Django 5.0.6 on 2024-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(default=False, upload_to='img'),
        ),
    ]
